// Generated by Wrangler on Thu Apr 25 2024 16:20:59 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	GOOGLE_CALLBACK_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	BUCKET: R2Bucket;
	DB: D1Database;
}
